name: Verify build (Node 24)

on:
  workflow_call:
    inputs:
      node-version:
        type: number
        description: 'Node version to use'
        required: true
        default: 24

# The GITHUB_TOKEN used by Dependabot has read-only permissions by default. We
# provide write permissions to this workflow so that comments can be left on
# the pull request.
#
# @see https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#changing-github_token-permissions
permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    name: Check built files

    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v7
      with:
        fetch-depth: 2

    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: ${{ format('{0}', inputs.node-version) }}
        cache: 'npm'

    - name: Update npm to latest
      run: npm install -g npm@latest

    - name: Verify Node dependency cache
      uses: actions/cache@v5
      with:
        path: ./node_modules
        key: node-dependencies-${{ hashFiles('package-lock.json') }}
        restore-keys: node-dependencies-

    - name: Install Node dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Capture Git status
      id: git
      shell: bash
      run: |
        {
          echo 'changes<<EOF'
          echo "$(git status --porcelain --untracked-files=all)"
          echo 'EOF'
          echo "nodeVersion=$(node --version)"
          echo "npmVersion=$(npm --version)"
        } >> $GITHUB_OUTPUT

    - name: Fail if changes detected
      shell: bash
      run: |
        if [[ -n "${{ steps.git.outputs.changes }}" ]]; then
          exit 1
        fi

    - name: Comment on pull request
      if: failure()
      uses: actions/github-script@v8
      with:
        script: |
          const output = `Changed files were detected after build. Please run project build workflows and check \`git status\` for any missed changes.

          \`\`\`
          ${{ steps.git.outputs.changes }}
          \`\`\`

          You may need to update your local NPM configuration if different than below:
          * Node ${{ steps.git.outputs.nodeVersion }}
          * NPM ${{ steps.git.outputs.npmVersion }}
          `;

          github.rest.issues.createComment({
            ...context.repo,
            issue_number: context.payload.pull_request.number,
            body: output
          })
